image: node:6.7.0

cache:
  paths:
    - node_modules/

stages:
  - deploy
  - deploy2

deploy:
  stage: deploy
  script:
    - cd /home/ops/production/marketDataGateway
    - git checkout master
    - git reset --hard HEAD
    - git clean -f -d
    - git pull
    - rm -rf /home/ops/production/marketDataGateway/crt
    - ln -s /home/ops/victor/crt /home/ops/production/marketDataGateway/crt
    - npm install --registry=https://registry.npm.taobao.org
    - rm -Rf dist
    - npm run compile
    - pm2 restart marketDataGateway
  only:
    - master
  tags:
    - deploy-ssh

deploy2:
  stage: deploy
  script:
    - cd /home/ops/production/marketDataGateway
    - git checkout master
    - git reset --hard HEAD
    - git clean -f -d
    - git pull
    - rm -rf /home/ops/production/marketDataGateway/crt
    - ln -s /home/ops/victor/crt /home/ops/production/marketDataGateway/crt
    - npm install --registry=https://registry.npm.taobao.org
    - rm -Rf dist
    - npm run compile
    - pm2 restart marketDataGateway
  only:
    - master
  tags:
    - ssh-backtest
